# Copyright 2022 Clastix
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  name:
    default: capsule
    description: "Multi Tenant Operator"
    type: string
  namespace:
    default: capsule-system
    description: "Capsule system namespace."
    type: string
  capsule-configuration-name:
    default: capsule-default
    description: "Capsule Configuration name."
    type: string
  user-groups:
    default: capsule.clastix.io
    description: "Comma-separated list of user groups (example: oil.capsule.io,gas.capsule.io,...)."
    type: string
  force-tenant-prefix:
    default: false
    description: "Force to have a tenant prefix."
    type: boolean
  protected-namespace-regex:
    default: ""
    description: "Disallows creation of namespaces matching the passed regexp."
    type: string
